language: rust
sudo: required
cache: cargo
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - nightly
  - beta
  - stable
script:
- cargo clean
- cargo build
- cargo test

after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --ciserver travis-ci --ignore-tests --coveralls $TRAVIS_JOB_ID
