language: rust
sudo: required
cache: cargo
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - nightly
  - beta
  - stable

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
